---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: certmanager
  data:
    - secretKey: credentials-certmanager
      remoteRef:
        key: homelab/certmanager
        property: credentials-certmanager
