apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-admin
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: miniflux-admin
  data:
    - secretKey: password
      remoteRef:
        key: homelab/miniflux
        property: admin_password
