apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-ci
  namespace: tekton-pipelines
secrets:
  - name: github-deploy-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-ci-triggers
  namespace: tekton-pipelines
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-triggers
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-ci-triggers
