apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-tag-push
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: "$(extensions.tag)"
    - name: git-url
      value: "$(body.repository.ssh_url)"
