apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: flowfin-webhook
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-ci
  triggers:
    - name: github-tag-push
      bindings:
        - ref: github-tag-push
      template:
        ref: flowfin-build-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref.startsWith('refs/tags/v')"
            - name: "overlays"
              value:
                - key: tag
                  expression: "body.ref.split('/')[2]"
