---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: homepage-api-keys
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: PROWLARR_API_KEY
    - secretKey: BAZARR_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: BAZARR_API_KEY
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: JELLYFIN_API_KEY
    - secretKey: JELLYSEERR_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: JELLYSEERR_API_KEY
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: homelab/homepage-api-keys
        property: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: homelab/homepage-api-keys
        property: QBITTORRENT_PASSWORD
    - secretKey: MINIFLUX_API_KEY
      remoteRef:
        key: homelab/homepage-api-keys
        property: MINIFLUX_API_KEY
