---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: external-dns
  data:
    - secretKey: credentials
      remoteRef:
        key: homelab/external-dns
        property: credentials
