---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-apps-apikeys
  namespace: media
  labels:
    app.kubernetes.io/part-of: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: arr-apps-apikeys
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: PROWLARR_API_KEY
    - secretKey: BAZARR_API_KEY
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: BAZARR_API_KEY
    - secretKey: JELLYSEERR_API_KEY
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: JELLYSEERR_API_KEY
    - secretKey: QBITTORRENT_HOST
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: QBITTORRENT_HOST
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: QBITTORRENT_PASSWORD
    - secretKey: QBITTORRENT_PORT
      remoteRef:
        key: homelab/arr-apps-apikeys
        property: QBITTORRENT_PORT
