---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-creds
  namespace: media
  labels:
    app.kubernetes.io/name: protonvpn-creds
    app.kubernetes.io/part-of: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: protonvpn-creds
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: homelab/protonvpn-creds
        property: OPENVPN_USER
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: homelab/protonvpn-creds
        property: OPENVPN_PASSWORD
