apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        revision: main
        directories:
          - path: applications/*/manifests
  template:
    metadata:
      # e.g. path="applications/homepage/manifests" → name=homepage-manifest"
      name: '{{ base (dir .path.path) }}-manifest'
    spec:
      # Using the default project for now
      project: default
      source:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ base (dir .path.path) }}'
      ignoreDifferences:
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[].remoteRef.conversionStrategy
            - .spec.data[].remoteRef.decodingStrategy
            - .spec.data[].remoteRef.metadataPolicy
            - .spec.dataFrom
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.containers[].image
            - .spec.template.spec.initContainers[]?.image
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.template.spec.containers[].image
            - .spec.template.spec.initContainers[]?.image
        - group: kyverno.io
          kind: ClusterPolicy
          jqPathExpressions:
            - .spec.rules[]?.skipBackgroundRequests
            - .spec.rules[]?.validate.allowExistingViolations
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=true